name: Daily prices (Tiingo → Supabase)

on:
  schedule:
    # Runs Mon–Fri at 22:30 UTC ≈ 6:30 pm ET
    - cron: "30 22 * * 1-5"
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: "Comma-separated tickers to rebuild (or 'ALL')"
        required: false
        default: ""

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: prices-daily
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          TIINGO_TOKEN: ${{ secrets.TIINGO_TOKEN }}
          FORCE_REBUILD: ${{ github.event.inputs.force_rebuild }}
        run: python update_prices_tiingo.py
